environment:
  matrix:
  - nodejs_version: "12"
  - nodejs_version: "14"
  - nodejs_version: "16"
  - nodejs_version: "18"
  - nodejs_version: "20"
  webp_version: "1.3.2"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: .\bin\download_webp.ps1

test_script:
  - cwebp -version
  - node --version
  - npm --version
  - npm test

build: off
