name: Run tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node-version: [12, 14, 16, 18, 20, 22, 23]
        runner: ['ubuntu-latest', 'windows-latest', 'ubuntu-22.04-arm']

    name: node ${{ matrix.node-version }} on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: ensure minimum npm version
        run: npm --version | grep -v -E '^6\.' || npm install -g npm@7

      - run: npm ci

      - name: Install webp (windows)
        if: startsWith(matrix.runner, 'windows')
        shell: pwsh
        run: .\bin\download_webp.ps1

      - name: Install webp
        if: startsWith(matrix.runner, 'ubuntu')
        run: sudo ./bin/install_webp

      - run: npm test
